import type { Task } from "./components/GanttChart";

export const projectData: Task[] = [
	{
		TaskID: 1,
		Resources: [1, 2],
		TaskName: "Project Initiation",
		StartDate: new Date("04/01/2024"),
		subtasks: [
			{
				TaskID: 2,
				TaskName: "Identify Site location",
				StartDate: new Date("04/01/2024"),
				Duration: 9,
				Progress: 50,
			},
			{
				TaskID: 3,
				TaskName: "Perform Soil test",
				StartDate: new Date("04/10/2024"),
				Duration: 5,
				Progress: 10,
				Predecessor: "2",
			},
			{
				TaskID: 4,
				TaskName: "Soil test report",
				StartDate: new Date("04/15/2024"),
				Duration: 5,
				Progress: 4,
				Predecessor: "3",
			},
			{
				TaskID: 5,
				TaskName: "Develop floor plan",
				StartDate: new Date("04/08/2024"),
				Duration: 10,
				Progress: 81,
				Predecessor: "4",
			},
			{
				TaskID: 6,
				TaskName: "List materials",
				StartDate: new Date("04/11/2024"),
				Duration: 5,
				Progress: 100,
				Predecessor: "5",
			},
			{
				TaskID: 7,
				TaskName: "Estimation approval",
				StartDate: new Date("04/16/2024"),
				Duration: 10,
				Progress: 63,
				Predecessor: "6",
			},
		],
	},
	{
		TaskID: 8,
		Resources: [2, 3],
		TaskName: "Project Planning",
		StartDate: new Date("04/16/2024"),
		EndDate: new Date("04/30/2024"),
		subtasks: [
			{
				TaskID: 9,
				TaskName: "Site Preparation",
				StartDate: new Date("04/16/2024"),
				Duration: 5,
				Progress: 100,
				Predecessor: "7",
			},
			{
				TaskID: 10,
				TaskName: "Material Procurement",
				StartDate: new Date("04/23/2024"),
				Duration: 4,
				Progress: 60,
				Predecessor: "9",
			},
			{
				TaskID: 11,
				TaskName: "Allocate resources",
				StartDate: new Date("04/23/2024"),
				Duration: 4,
				Progress: 75,
				Predecessor: "9",
			},
			{
				TaskID: 12,
				TaskName: "Identify potential risks",
				StartDate: new Date("04/29/2024"),
				Duration: 2,
				Progress: 30,
				Predecessor: "11",
			},
		],
	},
	{
		TaskID: 13,
		Resources: [3, 4],
		TaskName: "Project Execution",
		StartDate: new Date("05/01/2024"),
		EndDate: new Date("07/18/2024"),
		subtasks: [
			{
				TaskID: 14,
				TaskName: "Foundation work",
				StartDate: new Date("05/01/2024"),
				Duration: 10,
				Progress: 50,
				Predecessor: "12",
			},
			{
				TaskID: 15,
				TaskName: "Framing and roofing",
				StartDate: new Date("05/15/2024"),
				Duration: 10,
				Progress: 50,
				Predecessor: "14",
			},
			{
				TaskID: 16,
				TaskName: "Exterior finishing",
				StartDate: new Date("05/29/2024"),
				Duration: 8,
				Progress: 50,
				Predecessor: "15",
			},
			{
				TaskID: 17,
				TaskName: "Interior plumbing and electrical",
				StartDate: new Date("06/10/2024"),
				Duration: 10,
				Progress: 50,
				Predecessor: "16",
			},
			{
				TaskID: 18,
				TaskName: "Insulation and drywall",
				StartDate: new Date("06/24/2024"),
				Duration: 10,
				Progress: 50,
				Predecessor: "17",
			},
			{
				TaskID: 19,
				TaskName: "Interior finishing",
				StartDate: new Date("07/08/2024"),
				Duration: 8,
				Progress: 50,
				Predecessor: "18",
			},
		],
	},
	{
		TaskID: 20,
		Resources: [4, 1],
		TaskName: "Project Completion",
		StartDate: new Date("07/18/2024"),
		EndDate: new Date("07/28/2024"),
		subtasks: [
			{
				TaskID: 21,
				TaskName: "Final inspection",
				StartDate: new Date("07/18/2024"),
				Duration: 5,
				Progress: 0,
				Predecessor: "19",
			},
			{
				TaskID: 22,
				TaskName: "Cleanup and site restoration",
				StartDate: new Date("07/25/2024"),
				Duration: 3,
				Progress: 0,
				Predecessor: "21",
			},
			{
				TaskID: 23,
				TaskName: "Project handover",
				StartDate: new Date("07/28/2024"),
				Duration: 0,
				Progress: 20,
				Predecessor: "22",
			},
		],
	},
];

export const projectResources = [
	{ ResourceId: 1, ResourceName: "Alice" },
	{ ResourceId: 2, ResourceName: "Bob" },
	{ ResourceId: 3, ResourceName: "Charlie" },
	{ ResourceId: 4, ResourceName: "Dana" },
];
